### ISSUE TITLE
Graphic overlay

### ISSUE THREAD

**Issue by Matrybean** [timothy003/mobilediscord#12]
After the latest discord update the whole graphic overlay of both light and dark theme got completely messed up. Unfortunately, it makes the app much harder to use, with messages in dark theme being pretty much unreadable and a lot of graphic elements (like little gray dots notifying on unread messages on servers and channels) not showing up

**Comment by timothy003** [comment]
What OS version?

**Comment by Matrybean** [comment]
Windows 10 for mobile, version 14393.2551, sorry I forgot to mention that earlier

**Comment by Voldemort1926** [comment]
I'm having the same exact problem as Matrybean. Same build of Windows 10.

**Comment by Voldemort1926** [comment]
Thank you
