### ISSUE TITLE
Swiping between columns stopped working

### ISSUE THREAD

**Issue by FlyingSlig** [timothy003/mobilediscord#2]
I've been using the app on my Lumia 640 lately and everything worked fine, however, for some reason, the ability to swipe between servers, chat and users columns isn't working anymore, making the app unusable. Is this my device's fault or did an update on Discord's site break that functionality?

I'm using Windows 10 Mobile Creators Update, by the way.

**Comment by nutterguy** [comment]
Broken on my 950XL as well. Not seen an app update recently so I'm guessing something on Discords side changed. :_(

**Comment by timothy003** [comment]
This should've been fixed 3 days ago. I wonder if Discord rolled back the changes temporarily or if something's caching my old CSS. Can you try loading the app now? I've changed the filenames to force an update.

**Comment by FlyingSlig** [comment]
That seemed to work, swipes are working again. Thanks!
