### ISSUE TITLE
Mobile text size is too big

### ISSUE THREAD

**Issue by Marocco2** [timothy003/mobilediscord#4]
Lumia 930, last W10M build
I'm using 140% text size, but in mobilediscord is overscaled

![wp_ss_20180807_0002](https://user-images.githubusercontent.com/3944248/43827637-9dba925e-9afa-11e8-902e-82e989356f46.png)
![wp_ss_20180807_0001](https://user-images.githubusercontent.com/3944248/43827639-9df06cbc-9afa-11e8-87be-d062bf8d2a9b.png)

**Comment by timothy003** [comment]
Thanks for your report. Is this happening in all servers/channels, or just one? And how did you set 140% text size?

**Comment by Marocco2** [comment]
All the servers (menu, file descriptions, icons) are involved.
I went to Settings>Ease of access > other settings > scale text
![wp_ss_20180808_0001](https://user-images.githubusercontent.com/3944248/43848540-719836a2-9b33-11e8-8594-104d5fc86c28.png)

**Comment by timothy003** [comment]
Thanks for the info. This is actually a bug in Edge. I recommend using display scaling instead of text scaling in general, but I've added a workaround that fixes the most glaring issues with text scaling.

**Comment by Marocco2** [comment]
Great! Now is better, thank you 👍
