### ISSUE TITLE
microphone access

### ISSUE THREAD

**Issue by AmonGerar** [timothy003/mobilediscord#6]
"you do not have any input devices enable. You must grant Discord access to your microphone in order to be able to observe input sensitivity i reinstaled like 4 times and still happens also i granted the permitions but still, this is in Discord windows mobile.

**Comment by ObesusBR** [comment]
![wp_ss_20181031_0001](https://user-images.githubusercontent.com/44671224/47864980-c48cbe80-ddd9-11e8-97b4-197f11552112.png)
Same here

**Comment by timothy003** [comment]
Thanks for your reports. Audio input should now be functional. Please restart the app and try again.
