### ISSUE TITLE
Not loading.

### ISSUE THREAD

**Issue by 4nother** [timothy003/mobilediscord#9]
The app is not working. It only shows an error saying that Discord cannot be loaded.

**Comment by 4nother** [comment]
It has worked before. This is the first time I have encountered this problem. I've tried reinstalling the applications, but it hasn't worked. Trying to press reload doesn't work, and stays on the "Failed to load" screen. My internet works fine, and the discord servers have no problems of their own. The code for the error is HTTP 403 if that helps.

**Comment by timothy003** [comment]
Thanks for alerting me. The Heroku dyno got assigned to a banned IP address. I've manually restarted it for now, but will add code to detect this and restart automatically.
